spring:
  datasource:
    username: root
    url: jdbc:mariadb://localhost:3307/zb_technicalchallenges
    driverClassName: org.mariadb.jdbc.Driver
    password: maria950912

  jpa:
    properties:
      hibernate:
        format_sql: 'true'
    hibernate:
      ddl-auto: create
    show-sql: 'true'

  redis:
    host: localhost
    port: 6379

  jwt:
    secret: ZeRoBaSeTeChNiCaLChAlLeNgEsByHyUnGJuN950912

  scheduler:
    reservationStillAvailableReviewing:
      cron: "0 0 0 * * *"